package week1.day1.exceptions;

public class ExceptionsPractice {

	public static int divide(int x, int y) throws RuntimeException {
		if (x == 10 ) {
			throw new IllegalArgumentException("No 10 allowed");
		}
		return x / y;
	}
	
	public static void main(String[] args) {
		// try/catch block
		try {
			// Code that "could" break goes here
			int x = divide(10, 0);
		} catch (ArithmeticException e) {
			System.out.println("Cannot divide by zero");

		} catch (IllegalArgumentException e) {
			// Handle the "bad" outcome
			// Put code that handles the edge cases
			System.out.println(e.getMessage());
		} catch (Exception e) {
			System.out.println("Generic exception");
		}
		System.out.println("Program finished");
	}
}
